drop database ECommerce;
CREATE DATABASE ECommerce;
USE ECommerce;



CREATE TABLE CLIENT(
Id_Client INT AUTO_INCREMENT PRIMARY KEY,
Name_Client VARCHAR(100) NOT NULL,
Email VARCHAR(50) NOT NULL,
Adress VARCHAR(100) NOT NULL
);

CREATE TABLE PRODUCT(
Id_Product INT AUTO_INCREMENT PRIMARY KEY,
Name_Product VARCHAR(100) NOT NULL,
Price FLOAT NOT NULL,
Description VARCHAR(500) NOT NULL
);

CREATE TABLE ORDERS (
    Id_Orders INT AUTO_INCREMENT PRIMARY KEY,
    Date_ DATE,
    Total FLOAT,
    Id_Client INT,
    CONSTRAINT FK_Client FOREIGN KEY (Id_Client) REFERENCES CLIENT(Id_Client)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE ORDER_DETAIL (
    Id_Order_Detail INT AUTO_INCREMENT PRIMARY KEY,
    Id_Order INT,
    Id_Products INT,
    total FLOAT NOT NULL,
    CONSTRAINT FK_Products FOREIGN KEY (Id_Products) REFERENCES PRODUCT(Id_Product)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT FK_OrderDetail FOREIGN KEY (Id_Order) REFERENCES ORDERS(Id_Orders)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

